/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ifttt.module';
import * as i2 from './editor/ifttt-editor.component.ngfactory';
import * as i3 from '@angular/forms';
export const IftttModuleNgFactory:i0.NgModuleFactory<i1.IftttModule> = i0.ɵcmf(i1.IftttModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.IftttEditorComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.ɵi,i3.ɵi,([] as any[])),i0.ɵmpd(512,
          i3.ɵba,i3.ɵba,([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),
          i0.ɵmpd(512,i1.IftttModule,i1.IftttModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZ2l0L0hhY2thdGhvbi8yMDE4LVNpdGVjb3Jwcy9zcmMvRmVhdHVyZS9JRlRUVC9jb2RlL0NvbW11bml0eS5GZWF0dXJlLklGVFRULkFuZ3VsYXIvaWZ0dHQvaWZ0dHQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2dpdC9IYWNrYXRob24vMjAxOC1TaXRlY29ycHMvc3JjL0ZlYXR1cmUvSUZUVFQvY29kZS9Db21tdW5pdHkuRmVhdHVyZS5JRlRUVC5Bbmd1bGFyL2lmdHR0L2lmdHR0Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
