---
ID: "2c2adde3-2853-4f29-a849-7e097d714b49"
Parent: "11d160cf-d33e-4343-b7b8-83bd7a5d4657"
Template: "11d160cf-d33e-4343-b7b8-83bd7a5d4657"
Path: /sitecore/templates/Feature/IFTTT Logging/Logging Rule/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180303T092517Z
    - ID: "2899b8f9-70c2-4b53-a89c-872cfc7e2047"
      Hint: Rule
      Type: Rules
      Value: |
        <ruleset>
          <rule
            uid="{5C3AC19C-3279-4F12-A55F-317A185296E3}">
            <conditions />
          </rule>
        </ruleset>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
