---
ID: "60027e5c-5424-4ebf-9b0b-7c86c643feca"
Parent: "bf0897fb-c36c-4c08-bf74-6816ebddcafa"
Template: "239f9cf4-e5a0-44e0-b342-0f32cd4c6d8b"
Path: /sitecore/system/Modules/IFTTT/Settings
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/32x32/folder_gear.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180224T181451Z
